# Generated by Django 4.2 on 2024-06-22 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_rename_user_profile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_renters',
            field=models.ManyToManyField(blank=True, related_name='favorited_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
