# Generated by Django 4.2 on 2024-06-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_genre'),
        ('profiles', '0004_alter_profile_favorite_renters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_renters',
        ),
        migrations.AddField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='games.game'),
        ),
    ]
