# Generated by Django 4.2 on 2024-06-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('platformer', 'Platformer'), ('racing', 'Racing'), ('rpg', 'RPG'), ('action', 'Action'), ('adventure', 'Adventure'), ('fighting', 'Fighting'), ('classic', 'Classic')], default='adventure', max_length=20),
        ),
    ]
